# Indexes
MIN_INDEX = 0
MAX_INDEX = 2
INDEX_RANGE = (MIN_INDEX..MAX_INDEX)

# Points
EMPTY_POINTS = 0
CROSS_POINT = 2
CIRCLE_POINT = 5
CROSS_WINNING_POINTS = CROSS_POINT * 3
CIRCLE_WINNING_POINTS = CIRCLE_POINT * 3

# Input
INPUT_HELP = "help"
INPUT_REGEX = /^[0-2]{2}$/

# Marks
MARK_X = "X"
MARK_O = "O"
MARK_EMPTY = " "

# Strings
BOARD_VERTICAL_SEPARATOR = "|"
BOARD_HORIZONTAL_SEPARATOR = "---#{BOARD_VERTICAL_SEPARATOR}---#{BOARD_VERTICAL_SEPARATOR}---\n"